=== CtrlC-CtrlV/megaman-mario/MegaManClone/MegaManClone/MegaManCloneContent/megamangamedefinition.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

<!-- Types -->
<xs:simpleType name="orderedPair">
  <xs:restriction base="xs:string">
    <xs:pattern value="([0-9])+,([0-9])+" />
  </xs:restriction>
</xs:simpleType>

<!-- Attributes -->
<xs:attribute name="blockType">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="question" />
      <xs:enumeration value="brick" />
      <xs:enumeration value="used" />
      <xs:enumeration value="pyramid" />
      <xs:enumeration value="pyramid2" />
      <xs:enumeration value="floor" />
      <xs:enumeration value="floor2" />
      <xs:enumeration value="hidden" />
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>
<xs:attribute name="enemyType">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="met" />
      <xs:enumeration value="wheelhog" />
      <xs:enumeration value="beeCopter" />
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>
<xs:attribute name="itemType">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="etank" />
      <xs:enumeration value="falconpowerup" />
      <xs:enumeration value="lifetank" />
      <xs:enumeration value="megamanhelmet" />
      <xs:enumeration value="zerohelmet" />
      <xs:enumeration value="flagpole" />
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>
<xs:attribute name="location" type="orderedPair" />

<!-- Stage components -->
<xs:element name="megaman">
  <xs:complexType>
    <xs:attribute ref="location" />
  </xs:complexType>
</xs:element>
<xs:element name="item">
  <xs:complexType>
    <xs:attribute ref="itemType" />
    <xs:attribute ref="location" use="optional"/>
  </xs:complexType>
</xs:element>
<xs:element name="block">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="item" minOccurs="0" />
    </xs:sequence>
    <xs:attribute ref="location" />
    <xs:attribute ref="blockType" />
  </xs:complexType>
</xs:element>
<xs:element name="platform">
  <xs:complexType>
    <xs:attribute ref="blockType" />
    <xs:attribute ref="location" />
    <xs:attribute name="size" type="orderedPair" />
  </xs:complexType>
</xs:element>
<xs:element name="enemy">
  <xs:complexType>
    <xs:attribute ref="enemyType" />
    <xs:attribute ref="location" />
  </xs:complexType>
</xs:element>

<!-- Describes a stage of play -->
<xs:element name="stage">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="megaman" minOccurs="1" maxOccurs="1" />
      <xs:element ref="platform" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="block" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="item" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="enemy" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="stageID" type="xs:string" />
    <xs:attribute name="background" type="xs:string" />
    <xs:attribute name="boundary" type="orderedPair" />
    <xs:attribute name="music" type="xs:string" />
    <xs:attribute name="time" type="xs:string" />
    <xs:attribute name="checkpoint" type="orderedPair" />
  </xs:complexType>
  <xs:unique name="uniqueStageID">
    <xs:selector xpath="stageID" />
    <xs:field xpath="." />
  </xs:unique>
</xs:element>

<!-- Root element -->
<xs:element name="megamangame">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="stage" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== CtrlC-CtrlV/megaman-mario/MegaManClone/MegaManClone/MegaManClone/bin/x86/Release/Content/config.xml
<?xml version="1.0" encoding="utf-8" ?>
<megamangame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="megamangamedefinition.xsd">
  <stage id="stage1-1" background="backgrounds/plainBG" boundary="212,15" music="music/001-mmu-prologue" time="400" checkpoint="100,12">
    
    <megaman location="1,12" />
    
    <!-- Floor -->
    <platform location="0,13" size="70,2" blockType="floor" />
    <platform location="72,13" size="15,2" blockType="floor"/>
    <platform location="89,13" size="64,2" blockType="floor" />
    <platform location="155,13" size="57,2" blockType="floor" />

    <!-- Pipes -->
    <platform location="31,11" size="2,2" blockType="pyramid" />
    <platform location="39,10" size="2,3" blockType="pyramid" />
    <platform location="47,9" size="2,4" blockType="pyramid" />
    <platform location="56,10" size="2,3" blockType="pyramid" />
    <platform location="163,11" size="2,2" blockType="pyramid"/>
    <platform location="179,11" size="2,2" blockType="pyramid"/> 
    
    <!-- Brick Platforms -->
    <platform location="81,5" size="8,1" blockType="brick" />
    <platform location="92,5" size="3,1" blockType="brick" />
    <platform location="123,5" size="3,1" blockType="brick"/>
    <platform location="131,9" size="2,1" blockType="brick" />
    <platform location="168,9" size="2,1" blockType="brick"/>
    
    <!-- Random Ramp Up and Down -->
    <platform location="136,12" size="4,1" blockType="pyramid"/>
    <platform location="137,11" size="3,1" blockType="pyramid"/>
    <platform location="138,10" size="2,1" blockType="pyramid"/>
    <platform location="139,9" size="1,1" blockType="pyramid"/>
    <platform location="142,12" size="4,1" blockType="pyramid"/>
    <platform location="142,11" size="3,1" blockType="pyramid"/>
    <platform location="142,10" size="2,1" blockType="pyramid"/>
    <platform location="142,9" size="1,1" blockType="pyramid"/>
    
    <!-- Ramp Up and Down with Pit of Death -->
    <platform location="148,12" size="5,1" blockType="pyramid"/>
    <platform location="149,11" size="4,1" blockType="pyramid"/>
    <platform location="150,10" size="3,1" blockType="pyramid"/>
    <platform location="151,9" size="2,1" blockType="pyramid"/>
    <platform location="155,12" size="4,1" blockType="pyramid"/>
    <platform location="155,11" size="3,1" blockType="pyramid"/>
    <platform location="155,10" size="2,1" blockType="pyramid"/>
    <platform location="155,9" size="1,1" blockType="pyramid"/>
    
    <!-- Ramp Before Flag Pole -->
    <platform location="181,12" size="9,1" blockType="pyramid"/>
    <platform location="182,11" size="8,1" blockType="pyramid"/>
    <platform location="183,10" size="7,1" blockType="pyramid"/>
    <platform location="184,9" size="6,1" blockType="pyramid"/>
    <platform location="185,8" size="5,1" blockType="pyramid"/>
    <platform location="186,7" size="4,1" blockType="pyramid"/>
    <platform location="187,6" size="3,1" blockType="pyramid"/>
    <platform location="188,5" size="2,1" blockType="pyramid"/>
    

    <!-- Interactable Blocks -->
    <block blockType="hidden" location="15,8" />
    <block blockType="question" location="17,9">
      <item itemType="etank" />
      <item itemType="zerohelmet" />
      <item itemType="falconpowerup" />
      <item itemType="lifetank"  />
    </block>
    <block blockType="hidden" location="19,8" />
    <block blockType="brick" location="21,9" >
      <item itemType="lifetank"/>
    </block>
    <!--item itemType="lifetank" location="21,8"/>
      <item itemType="lifetank" location="21,8" />
      <item itemType="lifetank" location="21,8" /-->
    <block blockType="question" location="22,9" />
    <block blockType="brick" location="23,9" />
    <block blockType="question" location="24,9" />
    <block blockType="brick" location="25,9" />
    <block blockType="hidden" location="27,8" />

    <block blockType="hidden" location="21,4" />
    <block blockType="question" location="23,5" />
    <block blockType="hidden" location="25,4" />
    
    <block blockType="question" location="64,8" />
    <block blockType="brick" location="78,9" />
    <block blockType="question" location="79,9" />
    <block blockType="brick" location="80,9" />
    <block blockType="question" location="95,5" />
    <block blockType="brick" location="95,9" />
    <block blockType="brick" location="102,9" />

    <block blockType="question" location="103,9" />
    <block blockType="question" location="108,9" />
    <block blockType="question" location="111,9" />
    <block blockType="question" location="111,5" />
    <block blockType="question" location="114,9" />
    
    <block blockType="brick" location="120,9" />
    <block blockType="brick" location="130,5" />
    <block blockType="question" location="131,5" />
    <block blockType="question" location="132,5" />
    <block blockType="brick" location="133,5" />
    
    <block blockType="question" location="170,9" />
    <block blockType="brick" location="171,9" />
    
    <!-- Hidden Blocks Make the World Go Round -->
    <block blockType="hidden" location="29,10" />
    <block blockType="hidden" location="34,10" />
    <block blockType="hidden" location="37,9" />
    <block blockType="hidden" location="42,9" />
    <block blockType="hidden" location="45,8" />
    <block blockType="hidden" location="50,8" />
    <block blockType="hidden" location="54,9" />
    <block blockType="hidden" location="59,9" />
    <block blockType="hidden" location="62,7" />
    <block blockType="hidden" location="66,7" />
    <block blockType="hidden" location="71,12" />
    <block blockType="hidden" location="76,8" />
    <block blockType="hidden" location="82,8" />
    <block blockType="hidden" location="80,4" />
    <block blockType="hidden" location="88,12" />
    <block blockType="hidden" location="90,4" />
    <block blockType="hidden" location="93,8" />
    <block blockType="hidden" location="97,4" />
    <block blockType="hidden" location="97,8" />
    <block blockType="hidden" location="100,8" />
    <block blockType="hidden" location="105,8" />
    <block blockType="hidden" location="106,8" />
    <block blockType="hidden" location="109,4" />
    <block blockType="hidden" location="110,8" />
    <block blockType="hidden" location="113,4" />
    <block blockType="hidden" location="113,8" />
    <block blockType="hidden" location="116,8" />
    <block blockType="hidden" location="118,8" />
    <block blockType="hidden" location="121,4" />
    <block blockType="hidden" location="122,8" />
    <block blockType="hidden" location="127,4" />
    <block blockType="hidden" location="128,4" />
    <block blockType="hidden" location="129,8" />
    <block blockType="hidden" location="134,8" />
    <block blockType="hidden" location="135,4" />
    <block blockType="hidden" location="134,11" /><!--First weird ramp-->
    <block blockType="hidden" location="135,10" />
    <block blockType="hidden" location="136,9" />
    <block blockType="hidden" location="137,8" />
    <block blockType="hidden" location="141,8" />
    <block blockType="hidden" location="144,8" />
    <block blockType="hidden" location="145,9" />
    <block blockType="hidden" location="146,10" />
    <block blockType="hidden" location="147,11" />
    <block blockType="hidden" location="148,11" />
    <block blockType="hidden" location="149,10" />
    <block blockType="hidden" location="150,9" />
    <block blockType="hidden" location="151,8" />
    <block blockType="hidden" location="154,8" />
    <block blockType="hidden" location="157,8" />
    <block blockType="hidden" location="158,9" />
    <block blockType="hidden" location="159,10" />
    <block blockType="hidden" location="160,11" />
    <block blockType="hidden" location="166,8" />
    <block blockType="hidden" location="172,8" />
    <block blockType="hidden" location="162,10" />
    <block blockType="hidden" location="165,10" />
    <block blockType="hidden" location="178,10" />
    <block blockType="hidden" location="182,9" />
    <block blockType="hidden" location="183,8" />
    <block blockType="hidden" location="184,7" />
    <block blockType="hidden" location="185,6" />
    <block blockType="hidden" location="186,5" />
    <block blockType="hidden" location="187,4" />
    <block blockType="hidden" location="190,4" />
    
    <!-- Who so ever passes the blocks of death shall answer me
    these questions three, DAREEE the other side he see! -->
    <block blockType="death" location="70,14" />
    <block blockType="death" location="71,14" />
    <block blockType="death" location="87,14" />
    <block blockType="death" location="88,14" />
    <block blockType="death" location="153,14" />
    <block blockType="death" location="154,14" />

    <!-- Static Items -->
    <!--
    <item itemType="etank" location="22,8"/>
    <item itemType="lifetank" location="23,12" />
    <item itemType="megamanhelmet" location="64,7" />
    <item itemType="zerohelmet" location="23,4" />
    <item itemType="etank" location="79,8" />
    <item itemType="lifetank" location="95,8" />
    <item itemType="etank" location="111,4" />
    <item itemType="falconpowerup" location="103,8"/>
    -->
    <item itemType="lifetank" location="11,7"/>
    <item itemType="lifetank" location="12,6"/>
    <item itemType="lifetank" location="13,5"/>
    <item itemType="lifetank" location="14,6"/>
    <item itemType="lifetank" location="15,7"/>
    <item itemType="lifetank" location="17,5"/>
    <item itemType="lifetank" location="23,2"/>
    <item itemType="lifetank" location="27,6"/>
    <item itemType="lifetank" location="29,7"/>
    <item itemType="lifetank" location="34,12"/> 
    
    <item itemType="lifetank" location="35,12"/>
    <item itemType="lifetank" location="36,12"/>
    <item itemType="lifetank" location="35,7"/>
    <item itemType="lifetank" location="43,12"/>
    <item itemType="lifetank" location="44,12"/>
